### ISSUE TITLE
ImportError : DINGOS_MANTIS_ACTIONABLES_CONTEXT_TAG_REGEX

### ISSUE THREAD

**Issue by aramirez84** [siemens/django-mantis-actionables#7]
When I install manage.py on fresh Ubuntu 14.04 installation I get error after command:
**(pip install -e . --proxy=$your_proxy ) | tee -a /home/mantis/ti/install.log**
`Obtaining file:///home/mantis/ti/django-mantis-actionables
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/mantis/ti/django-mantis-actionables/setup.py", line 7, in <module>
        import mantis_actionables
      File "mantis_actionables/__init__.py", line 5, in <module>
        from dingos import DINGOS_MANTIS_ACTIONABLES_CONTEXT_TAG_REGEX
    ImportError: cannot import name DINGOS_MANTIS_ACTIONABLES_CONTEXT_TAG_REGEX
`

**Comment by bgro** [comment]
Archiving MANTIS (it is not maintained any longer)
